In [26]:
#El kolli montassar 
#matricule : 20137575
#2 algorithme primal affine 
#3 probleme du fermier 
using LinearAlgebra
using JuMP, Clp

In [27]:
#exercie2 : algorithme primal affine julia  
mutable struct interiorPoint
    z::Int64 # numéro de l'itération à laquelle on est rendu
    Z::Int64 # nombre maximal d'itérations
    x::Vector # valeur de la solution courante
end
primalAffine = interiorPoint(0, 1000,[])

interiorPoint(0, 1000, Any[])

In [28]:
function (primalAffine::interiorPoint)(x0::Vector, c::Vector, A::Matrix, b::Vector,
                                          e::Float64 = 1e-6)

    
    primalAffine.x = copy(x0)
    n= length(primalAffine.x)
    
    obj = dot(c,primalAffine.x)
    deltac = abs(obj)+2
    deltax=Inf*ones(n)
    
    Y=0.995 
    z = 0  
    Z = 1000    #condition d'arret
   
    while((z < Z) && ( deltac > e * max(abs(obj), 1))) 
        z += 1   
        X = diagm(primalAffine.x)
        deltax = -(I-(A*X)'*(((A*X)*(A*X)')\(A*X)))*X*c   #trouver le delta x  
        
    
        i = 0
        xi = 0
        for j = 1:n
            if -deltax[j] > xi
                xi = - deltax[j]
                i = j 
            end
        end
        if (i == 0 ) 
            println("Problem non borné: ! ")
            break;
        end
        a = Y/xi
        newx = primalAffine.x+a*X*deltax
        newobj = dot(c,newx)
        deltac = obj - newobj
        obj = newobj
        primalAffine.x = newx
       
    end
end

In [29]:
#resolution du probleme de l'exercice2 avec l'algorithme primal affine vu en classe

c = [-1; -2; 0; 0]
A = [1 1 1 0;
     -1 1 0 1]
b = [2; 1]
x0 = [1; 1; 0; 1]
primalAffine(x0, c, A, b)
primalAffine.x

4-element Array{Float64,1}:
 0.5000000015140852
 1.4999999877825996
 0.0
 6.24999999999994e-10

In [30]:
#donc les solution pour notre probleme sont x1 = 0.5 , x2 = 1.5  et Z= 0.5 + 2*1.5 = 3.5 

In [31]:
#resolution du probleme de du fermier avec l'algorithme primal affine vu en classe
#matrice du probleme sous la forme standard
c = [150 ; 230 ; 260 ; 238 ; 210 ; -170 ; -150 ; -36 ; -10 ; 0 ; 0 ; 0 ; 0 ; 0]
A = [1 1 1 0 0 0 0 0 0 1 0 0 0 0 ; 
     2.5 0 0 1 0 -1 0 0 0 0 -1 0 0 0 ;
     0 3 0 0 1 0 -1 0 0 0 0 -1 0 0 ;
     0 0 -20 0 0 0 0 1 1 0 0 0 1 0;
     0 0 0 0 0 0 0 1 0 0 0 0 0 1]
b = [500 ; 200 ; 240 ; 0 ; 6000]

5-element Array{Int64,1}:
  500
  200
  240
    0
 6000

In [32]:
x0 = [100 ; 100 ; 100 ; 50 ; 50 ; 50 ; 50 ; 500 ; 500]

9-element Array{Int64,1}:
 100
 100
 100
  50
  50
  50
  50
 500
 500

In [33]:
A[:,1:9]*x0-b

5-element Array{Float64,1}:
  -200.0
    50.0
    60.0
 -1000.0
 -5500.0

In [34]:
x0 = [x0 ; 200 ; 50 ; 60 ; 1000 ; 5500]

14-element Array{Int64,1}:
  100
  100
  100
   50
   50
   50
   50
  500
  500
  200
   50
   60
 1000
 5500

In [35]:
primalAffine(x0, c, A, b)

In [36]:
primalAffine.x

14-element Array{Float64,1}:
  119.99998810610988
   80.0000215960843
  299.9999901045849
    1.6127271609297502e-5
    1.0893358795261785e-5
   99.99998584741634
    5.829926195394697e-5
 5999.999479600694
    0.00027204786197936075
    1.059335855282812e-6
    6.146273179931968e-7
    1.7113391368395533e-5
    6.199823289310679e-5
    0.0005376781443152195

In [37]:
#les solution du probleme sont : (120 , 80 , 300) partie de terre alloué pour chaque plante ble , mais , betrave 
#solution optimale